apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: podinfo
  namespace: podinfo
spec:
  components:
    - name: podinfo # helm chart release name
      type: webapp-chart # definition = helm chart
      settings: # helm chart values
        cache: redis-master.redis:6379
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          path: "/"
